-- Room grouping: a device belongs to zero or one room (a Home Assistant "area"). Rooms carry no
-- behavior of their own; a device references its room through a nullable foreign key.

create table rooms (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

alter table devices add column room_id bigint;
alter table devices add constraint fk_devices_room foreign key (room_id) references rooms (id);
