-- Floor grouping: a room belongs to zero or one floor (a Home Assistant "floor"). Floors carry no
-- behavior of their own; a room references its floor through a nullable foreign key.

create table floors (
    id    bigint generated by default as identity primary key,
    name  varchar(255) not null unique,
    level integer not null
);

alter table rooms add column floor_id bigint;
alter table rooms add constraint fk_rooms_floor foreign key (floor_id) references floors (id);
