-- Automations: a rule runs its actions when a trigger fires and its conditions hold. The aggregate
-- owns three ordered child tables (triggers, conditions, actions); position is the list index that
-- keeps each stable across reloads. Enum-backed columns are plain varchar, matching V1, so the same
-- migration runs unchanged against another database later.

create table automations (
    id      bigint generated by default as identity primary key,
    name    varchar(255) not null,
    enabled boolean      not null
);

-- A device is referenced by id, without a foreign key on purpose: an automation outlives the
-- devices it names, so removing a device must not delete a rule. A stale reference is handled at
-- run time (the action is skipped and logged, a condition simply does not hold).

create table automation_triggers (
    id            bigint           generated by default as identity primary key,
    automation_id bigint           not null,
    position      integer          not null,
    kind          varchar(255)     not null,
    device_id     bigint           not null,
    sensor_key    varchar(255),
    comparison    varchar(255),
    threshold     double precision,
    constraint fk_automation_triggers_automation
        foreign key (automation_id) references automations (id)
);

create table automation_conditions (
    id            bigint       generated by default as identity primary key,
    automation_id bigint       not null,
    position      integer      not null,
    kind          varchar(255) not null,
    device_id     bigint       not null,
    state_key     varchar(255),
    expected      varchar(255),
    constraint fk_automation_conditions_automation
        foreign key (automation_id) references automations (id)
);

create table automation_actions (
    id                  bigint       generated by default as identity primary key,
    automation_id       bigint       not null,
    position            integer      not null,
    kind                varchar(255) not null,
    device_id           bigint       not null,
    on_state            boolean,
    brightness          integer,
    color_temperature_k integer,
    constraint fk_automation_actions_automation
        foreign key (automation_id) references automations (id)
);
