-- Sensor reading history for the trend charts: every numeric reading is appended here, and a
-- scheduled job prunes rows past the retention window. The index serves the per-sensor time-window
-- queries the charts run.

create table sensor_reading_history (
  id bigint generated by default as identity primary key,
  device_id varchar(255) not null,
  sensor_key varchar(255) not null,
  reading_value double precision not null,
  recorded_at timestamp(6) with time zone not null
);

create index idx_reading_history_series
  on sensor_reading_history (device_id, sensor_key, recorded_at);
