-- Initial schema for the device registry: a device, its capabilities and runtime state, and the
-- sensors it declares with their latest reading. This baseline owns the schema that the JPA
-- entities validate against (spring.jpa.hibernate.ddl-auto=validate). Enum-backed columns are
-- plain varchar so the same migration runs unchanged against another database later.

create table devices (
    id           bigint generated by default as identity primary key,
    external_id  varchar(255) not null unique,
    name         varchar(255) not null,
    type         varchar(255) not null,
    adapter_type varchar(255)
);

create table device_capabilities (
    device_id  bigint       not null,
    capability varchar(255) not null,
    primary key (device_id, capability),
    constraint fk_device_capabilities_device foreign key (device_id) references devices (id)
);

create table device_state (
    device_id   bigint       not null,
    state_key   varchar(255) not null,
    state_value varchar(255) not null,
    primary key (device_id, state_key),
    constraint fk_device_state_device foreign key (device_id) references devices (id)
);

create table sensors (
    id            bigint generated by default as identity primary key,
    device_id     bigint,
    sensor_key    varchar(255) not null,
    type          varchar(255) not null,
    unit          varchar(255) not null,
    reading_value varchar(255),
    updated_at    timestamp(6) with time zone,
    constraint fk_sensors_device foreign key (device_id) references devices (id)
);
